name: Garantia de Qualidade

on: 
  push:
    branches:
      - release
  workflow_dispatch:

jobs:

  install-and-test:

    runs-on: ubuntu-latest

    steps: 
      - name: Carregar código do repositório
        uses: actions/checkout@v4
      
      - name: Configurar ambiente Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci
      
      - name: Executar Testes
        run: npm test
    